FROM node:20-alpine

WORKDIR /usr/src/app

# Declare all build-time arguments
ARG NEXT_PUBLIC_RECAPTCHA_SITE_KEY
ARG NEXT_PUBLIC_SERVER_BASE_URL
ARG RECAPTCHA_SECRET_KEY
ARG NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY  
ARG NODE_ENV=production

# Set environment variables during build
ENV NEXT_PUBLIC_RECAPTCHA_SITE_KEY=$NEXT_PUBLIC_RECAPTCHA_SITE_KEY
ENV NEXT_PUBLIC_SERVER_BASE_URL=$NEXT_PUBLIC_SERVER_BASE_URL
ENV RECAPTCHA_SECRET_KEY=$RECAPTCHA_SECRET_KEY
ENV NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY=$NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY
ENV NODE_ENV=$NODE_ENV

# Install dependencies first for caching
COPY package*.json ./
RUN npm install --force --no-cache

# Copy rest of the code
COPY . .

# Build the app
RUN npm run build

EXPOSE 3000

# Set runtime env variables again (optional)
ENV NEXT_PUBLIC_RECAPTCHA_SITE_KEY=$NEXT_PUBLIC_RECAPTCHA_SITE_KEY
ENV NEXT_PUBLIC_SERVER_BASE_URL=$NEXT_PUBLIC_SERVER_BASE_URL
ENV RECAPTCHA_SECRET_KEY=$RECAPTCHA_SECRET_KEY
ENV NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY=$NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY
ENV NODE_ENV=$NODE_ENV

CMD ["npm", "start"]
